import React from 'react';
import { ClipboardCheck, Download, Printer, Share2 } from 'lucide-react';

export default function SoapNoteViewer({ data }) {
  // We prioritize the translated version if available, otherwise English
  const soap = data.soap_marathi || data.soap_english;
  const isTranslated = !!data.soap_marathi;

  const sections = [
    { 
      id: 'S', 
      title: 'Subjective', 
      content: soap.subjective, 
      color: 'text-blue-600', 
      bg: 'bg-blue-50',
      description: 'Patient concerns and history'
    },
    { 
      id: 'O', 
      title: 'Objective', 
      content: soap.objective, 
      color: 'text-indigo-600', 
      bg: 'bg-indigo-50',
      description: 'Vitals and physical findings'
    },
    { 
      id: 'A', 
      title: 'Assessment', 
      content: soap.assessment, 
      color: 'text-purple-600', 
      bg: 'bg-purple-50',
      description: 'Diagnosis and clinical logic'
    },
    { 
      id: 'P', 
      title: 'Plan', 
      content: soap.plan, 
      color: 'text-emerald-600', 
      bg: 'bg-emerald-50',
      description: 'Treatments and follow-ups'
    },
  ];

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-700">
      {/* Header Actions */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-200 pb-6">
        <div>
          <h2 className="text-3xl font-black text-slate-900 flex items-center gap-3">
            <ClipboardCheck className="text-emerald-500" size={32} /> 
            Clinical Record 
            {isTranslated && <span className="text-sm font-bold bg-blue-100 text-blue-600 px-3 py-1 rounded-full uppercase tracking-widest">Marathi Refined</span>}
          </h2>
          <p className="text-slate-500 font-medium mt-1">Generated by NER-RAG Pipeline • Session ID: {data.session_id}</p>
        </div>
        
        <div className="flex gap-2">
          <button className="flex items-center gap-2 px-4 py-2 bg-white border border-slate-200 rounded-xl text-sm font-bold text-slate-600 hover:bg-slate-50 transition">
            <Printer size={16}/> Print
          </button>
          <button className="flex items-center gap-2 px-4 py-2 bg-brand-600 rounded-xl text-sm font-bold text-white hover:bg-brand-700 shadow-lg shadow-brand-100 transition">
            <Download size={16}/> Export PDF
          </button>
        </div>
      </div>

      {/* SOAP Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {sections.map((sec) => (
          <div key={sec.id} className="group bg-white rounded-[2.5rem] p-8 border border-slate-100 shadow-sm hover:shadow-md transition-all duration-300">
            <div className="flex items-start justify-between mb-6">
              <div className="flex items-center gap-4">
                <div className={`w-14 h-14 ${sec.bg} ${sec.color} rounded-2xl flex items-center justify-center font-black text-2xl shadow-sm group-hover:scale-110 transition-transform`}>
                  {sec.id}
                </div>
                <div>
                  <h3 className="font-black text-slate-800 uppercase tracking-[0.15em] text-xs">{sec.title}</h3>
                  <p className="text-[10px] text-slate-400 font-bold uppercase tracking-widest mt-0.5">{sec.description}</p>
                </div>
              </div>
            </div>
            
            <div className="bg-slate-50/50 rounded-3xl p-6 border border-transparent group-hover:border-slate-100 transition-colors">
              <p className="text-slate-700 leading-relaxed font-medium text-lg italic whitespace-pre-wrap">
                {sec.content || "Extraction in progress..."}
              </p>
            </div>
          </div>
        ))}
      </div>

      {/* Metadata / NER Tags (Optional display from your backend result) */}
      {data.entities && (
        <div className="bg-white rounded-[2rem] p-8 border border-slate-100 shadow-sm">
          <h4 className="text-xs font-black text-slate-400 uppercase tracking-widest mb-4">NER Medical Entities Detected</h4>
          <div className="flex flex-wrap gap-2">
             {data.entities.patient?.map((e, i) => (
               <span key={i} className="px-3 py-1 bg-brand-50 text-brand-700 text-[10px] font-bold rounded-full border border-brand-100 uppercase tracking-wider">
                 💊 {e.text}
               </span>
             ))}
          </div>
        </div>
      )}
    </div>
  );
}