import React from 'react';
import { ClipboardCheck, Download, Printer } from 'lucide-react';

export default function SoapNoteViewer({ data }) {
  // Resolve the target language from the response
  const targetLang = data.target_language || 'marathi';
  const targetKey  = `soap_${targetLang}`;

  const englishSoap = data.soap_english || {};
  const targetSoap  = data[targetKey]   || {};
  const showBilingual = targetLang !== 'english' && !!data[targetKey];

  const langLabel = {
    marathi: 'मराठी',
    hindi:   'हिन्दी',
    english: 'English',
  }[targetLang] || targetLang;

  const sectionMeta = [
    { key: 'subjective', id: 'S', title: 'Subjective', color: 'text-blue-600',    bg: 'bg-blue-50',    desc: 'Patient concerns and history' },
    { key: 'objective',  id: 'O', title: 'Objective',  color: 'text-indigo-600',  bg: 'bg-indigo-50',  desc: 'Vitals and physical findings' },
    { key: 'assessment', id: 'A', title: 'Assessment', color: 'text-purple-600',  bg: 'bg-purple-50',  desc: 'Diagnosis and clinical logic' },
    { key: 'plan',       id: 'P', title: 'Plan',       color: 'text-emerald-600', bg: 'bg-emerald-50', desc: 'Treatments and follow-ups' },
  ];

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-700">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-200 pb-6">
        <div>
          <h2 className="text-3xl font-black text-slate-900 flex items-center gap-3">
            <ClipboardCheck className="text-emerald-500" size={32} />
            Clinical Record
            {showBilingual && (
              <span className="text-sm font-bold bg-blue-100 text-blue-600 px-3 py-1 rounded-full uppercase tracking-widest">
                {langLabel} + English
              </span>
            )}
          </h2>
          <p className="text-slate-500 font-medium mt-1">
            Generated by NER-RAG Pipeline •
            Session: <strong>{data.session_id || '—'}</strong> •
            Lang: <strong>{data.input_language || '—'}</strong> →
            <strong> {targetLang}</strong> •
            Time:
            <strong className="ml-2">{data.metadata?.processing_time || '—'}</strong>
            {data.metadata?.client_processing_time && (
              <span className="text-xs text-slate-400 ml-3">(client: {data.metadata.client_processing_time})</span>
            )}
            {data.metadata?.server_processing_time && (
              <span className="text-xs text-slate-400 ml-3">(server: {data.metadata.server_processing_time})</span>
            )}
          </p>
        </div>

        <div className="flex gap-2">
          <button className="flex items-center gap-2 px-4 py-2 bg-white border border-slate-200 rounded-xl text-sm font-bold text-slate-600 hover:bg-slate-50 transition">
            <Printer size={16} /> Print
          </button>
          <button className="flex items-center gap-2 px-4 py-2 bg-brand-600 rounded-xl text-sm font-bold text-white hover:bg-brand-700 shadow-lg shadow-brand-100 transition">
            <Download size={16} /> Export PDF
          </button>
        </div>
      </div>

      {/* SOAP Sections */}
      <div className="space-y-6">
        {sectionMeta.map((sec) => (
          <div key={sec.key} className="group bg-white rounded-[2rem] border border-slate-100 shadow-sm hover:shadow-md transition-all duration-300 overflow-hidden">
            {/* Section header */}
            <div className={`flex items-center gap-4 px-8 py-4 ${sec.bg}`}>
              <div className={`w-12 h-12 bg-white ${sec.color} rounded-xl flex items-center justify-center font-black text-xl shadow-sm group-hover:scale-110 transition-transform`}>
                {sec.id}
              </div>
              <div>
                <h3 className="font-black text-slate-800 uppercase tracking-[0.15em] text-sm">{sec.title}</h3>
                <p className="text-[10px] text-slate-500 font-bold uppercase tracking-widest">{sec.desc}</p>
              </div>
            </div>

            {/* Content: bilingual side-by-side or single column */}
            <div className={`grid ${showBilingual ? 'md:grid-cols-2' : 'grid-cols-1'} divide-x divide-slate-100`}>
              {/* English */}
              <div className="p-8">
                <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-3">English</p>
                <p className="text-slate-700 leading-relaxed font-medium text-base whitespace-pre-wrap">
                  {englishSoap[sec.key] || <span className="italic text-slate-400">Extraction in progress…</span>}
                </p>
              </div>

              {/* Translated column (only when bilingual) */}
              {showBilingual && (
                <div className="p-8 bg-amber-50/40">
                  <p className="text-[10px] font-black text-blue-500 uppercase tracking-widest mb-3">{langLabel}</p>
                  <p className="text-slate-700 leading-relaxed font-medium text-base whitespace-pre-wrap">
                    {targetSoap[sec.key] || <span className="italic text-slate-400">अनुवाद प्रगतीत…</span>}
                  </p>
                </div>
              )}
            </div>
          </div>
        ))}
      </div>

      {/* NER Entities */}
      {data.entities && (
        <div className="bg-white rounded-[2rem] p-8 border border-slate-100 shadow-sm">
          <h4 className="text-xs font-black text-slate-400 uppercase tracking-widest mb-4">NER Medical Entities Detected</h4>
          <div className="flex flex-wrap gap-2">
            {data.entities.patient?.map((e, i) => (
              <span key={i} className="px-3 py-1 bg-brand-50 text-brand-700 text-[10px] font-bold rounded-full border border-brand-100 uppercase tracking-wider">
                💊 {e.text || e}
              </span>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}